### ISSUE TITLE
Onderzoek clientenraad Nijmegen gebruik wallet

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/Innovatie-ID-wallet#15]
```[tasklist]
### Tasks
- [x] Wendy vraagt clientenraad naar medewerking
- [x] Ink maakt een opzet met vragen
- [x] Innovalor kijkt naar de onderzoeken
```

**Comment by wvdeeckhout** [comment]
Deze sluit ik, omdat de clientenraad meedoet in de algemene gebruikersonderzoeken.
