### ISSUE TITLE
Toewerken naar een multi-wallet proeftuin en uitbreiden van attributen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/Innovatie-ID-wallet#4]
Eerste stap zetten om meerdere wallets bij deze proeftuin te betrekken en andere bronhouders zoals UWV en KVK te betrekken.

```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/Innovatie-ID-wallet/issues/19
- [ ] https://github.com/GemeenteNijmegen/Innovatie-ID-wallet/issues/20
- [ ] https://github.com/GemeenteNijmegen/Innovatie-ID-wallet/issues/21
- [ ] https://github.com/GemeenteNijmegen/Innovatie-ID-wallet/issues/22
- [ ] https://github.com/GemeenteNijmegen/Innovatie-ID-wallet/issues/23
- [ ] https://github.com/GemeenteNijmegen/Innovatie-ID-wallet/issues/46
```

**Comment by wvdeeckhout** [comment]
![Image](https://github.com/user-attachments/assets/92b8e4bd-02eb-411b-8d24-8fe8fe090a5b)

**Comment by wvdeeckhout** [comment]
![Image](https://github.com/user-attachments/assets/ba08d84f-ab93-4112-8d20-ca14bc028884)

**Comment by wvdeeckhout** [comment]
Helaas lukt het niet om andere bronnen aan te laten sluiten, waardoor andere wallets weinig toegevoegde waarde hebben.
In dit project steken we hier geen energie meer in en sluit ik deze.
