### ISSUE TITLE
Use case Stadspas: totaaloverzicht

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/Innovatie-ID-wallet#5]
```[tasklist]
### Tasks
- [ ] Doel van de stadspas en afbakening
- [ ] Probleem schetsen/huidig proces inclusief knelpunten
- [ ] Bepalen opdrachtgever
- [ ] bepalen doelgroep
- [ ] bepalen benodigde infrastructuur nieuwe stadspas
- [ ] bepalen data en stakeholders
- [ ] herontwerp proces
- [ ] proces in proeftuin inrichten
- [ ] gebruikersonderzoek: doelgroep laten testen
- [ ] vervolgstappen bepalen
- [ ] faseren MVP's stadspas
```

**Comment by wvdeeckhout** [comment]
Deze is verder niet meer opgepakt. Geen wens binnen Nijmegen hiervoor.
